name: Deploy to GitHub pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Publish .NET Core Project
      run: dotnet publish pubgstats.csproj -c Release -o release

    # - name: Change base-tag in index.html from / to pubgstats
    #   run: sed -i ‘s/<base href=”\/” \/>/<base href=”\/pubgstats\/” \/>/g’ release/wwwroot/index.html

    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll  

    - name: Commit wwwroot to GitHub pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: release/wwwroot